apiVersion: batch/v1
kind: Job
metadata:
  name: "{name}"
  annotations:
    ortStage: analyzer
spec:
  template:
    spec:
      volumes:
        - name: ort-scratch
          persistentVolumeClaim:
            claimName: "{parent_name}-pvc"
        - name: ort-config-volume
          configMap:
            name: ort-config
            items:
              - key: config.yml
                path: config.yml
      initContainers:
        - name: cleanup
          image: alpine/git:v2.36.3
          command:
            - "rm"
            - "-rf"
            - "/opt/ort-scratch/{parent_name}"
          volumeMounts:
            - name: ort-scratch
              mountPath: /opt/ort-scratch
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "500m"
        - name: git
          image: alpine/git:v2.36.3
          command:
            - "git"
            - "clone"
            - "--depth"
            - "1"
            - "{repo_url}"
            - "/opt/ort-scratch/{parent_name}"
          volumeMounts:
            - name: ort-scratch
              mountPath: /opt/ort-scratch
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "500m"
        - name: fix-perms
          image: alpine/git:v2.36.3
          command:
            - "chmod"
            - "777"
            - "/opt/ort-scratch/{parent_name}"
          volumeMounts:
            - name: ort-scratch
              mountPath: /opt/ort-scratch
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "500m"
      containers:
        - name: ort
          image: haikoschol/oss-review-toolkit:latest
          args:
            - "--info"
            - "analyze"
            - "-i"
            - "/opt/ort-scratch/{parent_name}"
            - "-o"
            - "/opt/ort-scratch/{parent_name}"
          env:
            - name: ORT_DATA_DIR
              value: /opt/ort-scratch
            - name: ORT_CONFIG_DIR
              value: /etc/ort
          volumeMounts:
            - name: ort-scratch
              mountPath: /opt/ort-scratch
            - name: ort-config-volume
              mountPath: /etc/ort
              readOnly: true
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "4"
      restartPolicy: Never
  backoffLimit: 0
