---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{parent_name}-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
