apiVersion: batch/v1
kind: Job
metadata:
  name: "{name}"
  annotations:
    ortStage: reporter
spec:
  template:
    spec:
      volumes:
        - name: ort-scratch
          persistentVolumeClaim:
            claimName: ort-scratch-pvc
        - name: ort-config-volume
          configMap:
            name: ort-config
            items:
              - key: config.yml
                path: config.yml
      containers:
      - name: ort
        image: haikoschol/oss-review-toolkit:latest
        args: ["--info", "report",  "--report-formats", "WebApp", "-i", "/opt/ort-scratch/{parent_name}/scan-result.yml", "-o", "/opt/ort-scratch/{parent_name}/"]
        volumeMounts:
          - name: ort-scratch
            mountPath: /opt/ort-scratch
          - name: ort-config-volume
            mountPath: /etc/ort
            readOnly: true
        resources:
          requests:
            memory: "500Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"
      restartPolicy: Never
  backoffLimit: 0
