apiVersion: batch/v1
kind: Job
metadata:
  name: "{name}"
  annotations:
    ortStage: scanner
spec:
  template:
    spec:
      volumes:
        - name: ort-scratch
          persistentVolumeClaim:
            claimName: "{parent_name}-pvc"
        - name: ort-config-volume
          configMap:
            name: ort-config
            items:
              - key: config.yml
                path: config.yml
      containers:
      - name: ort
        image: haikoschol/oss-review-toolkit:latest
        args: ["--info", "scan",  "-i", "/opt/ort-scratch/{parent_name}/analyzer-result.yml", "-o", "/opt/ort-scratch/{parent_name}/"]
        volumeMounts:
          - name: ort-scratch
            mountPath: /opt/ort-scratch
          - name: ort-config-volume
            mountPath: /etc/ort
            readOnly: true
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
      restartPolicy: Never
  backoffLimit: 0
